using System;
using UnityEngine;

namespace PVPManager
{
	public class PvP_FakeName
	{
		internal static string GetRandomName()
		{
			int num = UnityEngine.Random.Range(0, PvP_FakeName.ListFakeName.Length);
			return PvP_FakeName.ListFakeName[num];
		}

		internal static string GetName(int id)
		{
			return PvP_FakeName.ListFakeName[id];
		}

		internal static string[] ListFakeName = new string[]
		{
			"Noal",
			"Faker",
			"Xihua",
			"SUPPER_FIRE",
			"Mr.007",
			"Alla",
			"สุปณิชา กระบวนสืบ",
			"ฉกาจ คล้ายทอง",
			"Valerio Davide",
			"Lok Meng",
			"Sheng_Long",
			"Galar Ramadan",
			"ChimSeDiNang",
			"Xibanu",
			"WuangFeng",
			"Dark_Cry",
			"RedDevil",
			"MunOnline",
			"MaiTrinh",
			"Hong_Bien",
			"Karsa Irawan",
			"Luhung Hidayat",
			"Jakubowski",
			"Louvenia",
			"Forrest",
			"Botond Borbély",
			"Λέων Ζερβός",
			"Jules Hussein",
			"BaBaBa",
			"Jakosi",
			"LeuLeu",
			"Ahihi",
			"سنان الرشدان",
			"대수 백",
			"goncalvesraquel",
			"yljubanic",
			"ashabalala",
			"Ada",
			"barlas24",
			" Isaac",
			"miguel95",
			"Wibisono",
			"gamblang81",
			"فیروز فنایی",
			"lshahbazi",
			"Аделина",
			"kovanusickovana",
			"昱然",
			"quiased",
			" Nicolaj",
			"Bruno",
			"ldavila",
			"Xavier",
			"tbrekke",
			"Tadeáš",
			"asimonovic",
			"Rebeca",
			"yanderson",
			"Noël",
			"xmarin",
			"Mijo Božikić",
			"sorajicdrinka",
			"Gonzalo",
			"mmartos",
			"Felicita",
			"dedrick13",
			"angelaakashaba",
			"yvette38",
			"Elwin",
			"Илиян",
			"Принов",
			"kvetoslavakruso",
			"Gert Sonntag",
			"rohdekarlludwig",
			"Sizwe",
			"contactmathe",
			"Norbert",
			"dionyz96",
			"Hành Nguyễn",
			"trieuanhtai",
			"Vince",
			"rita44",
			"მადონა",
			"გასანოვი",
			"jokhadzeteona",
			"BTKhaf4P",
			"مشاري",
			"melhemrami",
			"Ралета",
			"bukusicralen",
			"Игісін",
			"Әжібай",
			"tetileutanabaj",
			"Љубиша",
			"draza87",
			"Madalena Paiva",
			"Cleopatra",
			"BernhardBrugger",
			"wmartin",
			"ansumaharjan",
			"Kikutitumarushukhu",
			"Tententen",
			"Sharabuzal",
			"Wat_3721",
			"Hell999",
			" 柏穎",
			"Вуило",
			"pavlija30",
			"হাসান",
			"তাবাসসুম",
			"phahamedaali"
		};
	}
}
