using System;

public enum EStarGame
{
	CLEAR,
	COMBO,
	TIME,
	HP_MAIN,
	REVIVE = 5,
	LAST_KILL_BOSS_BY,
	KILL_ENEMY_BY,
	KILL_ENEMY_TRUCK = 9,
	DONT_USE_WEAPON,
	USE_SKILL_BY,
	DONT_USE_SKILL = 14,
	DONT_STOP_JETPACK,
	DESTROY_CH_47,
	KILL_ENEMY_WITH_GUN,
	REACH_COMBO_WITH_GUN
}
